services:
  - type: web
    name: job-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-portal-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: job-portal-db
    databaseName: job_portal
    user: job_portal_user