services:
  - type: web
    name: worktoday-job-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: sqlite-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        value: worktoday-secret-key-2024